import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./Components/Nav";
import Provider from "./Components/Provider";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./Components/Footer";
import { Toaster } from "react-hot-toast";
// metadata for better SEO
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-customGray w-full overflow-x-hidden relative`}
      >
        {/* Same as */}
        <Toaster/>
        <Provider>
          <Nav />
          {children}
          {/* <Footer/> */}
        </Provider>
      </body>
    </html>
  );
}
