import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./Components/Nav";
import Provider from "./Components/Provider";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-customGray w-full overflow-x-hidden`}
      >
          <Toaster position="bottom-right" reverseOrder={false} />
        <Provider>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  );
}
